/**
 * @file rng.c
 * @brief Random number generation — Mersenne Twister & Box-Muller
 *
 * ============================================================================
 * WHY CUSTOM RNG INSTEAD OF libc rand()?
 * ============================================================================
 *
 * 1. rand() from stdlib.h is TERRIBLE for Monte Carlo:
 *    - Period is only 2^31-1 (about 2 billion numbers). With 500k paths x
 *      252 steps = 126 million normals, we'd cycle through rand()'s period
 *      multiple times, introducing correlations.
 *    - Many implementations use a simple LCG (Linear Congruential Generator)
 *      that fails statistical tests for randomness.
 *    - RAND_MAX is only 32767 on some systems (Windows MSVC), giving
 *      terrible granularity for uniforms.
 *
 * 2. Mersenne Twister (MT19937):
 *    - Period of 2^19937-1: effectively infinite for our purposes.
 *      If you generated 1 billion numbers per second, you'd need ~10^6000
 *      years to cycle.
 *    - 623-dimensional equidistribution: any sequence of 623 consecutive
 *      32-bit integers is uniformly distributed.
 *    - Passes the DIEHARD and TestU01 statistical test suites.
 *    - Deterministic with a known seed → perfectly reproducible simulations.
 *
 * 3. Box-Muller for Normal Random Variables:
 *    - Problem: How to generate N(0,1) from Uniform(0,1)?
 *    - Solution: Box-Muller transform.
 *      If U1, U2 ~ Uniform(0,1) independent, then:
 *        Z1 = sqrt(-2*ln(U1)) * cos(2*pi*U2)
 *        Z2 = sqrt(-2*ln(U1)) * sin(2*pi*U2)
 *      are independent N(0,1).
 *    - We cache Z2 and return it on the next call to avoid wasting
 *      a uniform sample. This means every call generates 2 uniforms
 *      on average, but only every other call.
 *
 * ============================================================================
 * DESIGN TRADEOFFS
 * ============================================================================
 *
 * - All functions take an explicit RNGState* parameter. No global state.
 *   This makes the RNG thread-safe and reentrant — important if we ever
 *   parallelize with OpenMP.
 * - The state is 2500 bytes (624 x 4 bytes for mt[] + a few fields).
 *   This comfortably fits in L1 cache.
 * - We use double-precision throughout. The uniform is generated by
 *   multiplying a 32-bit integer by 2^-32 exactly.
 *
 * ============================================================================
 * REFERENCES
 * ============================================================================
 * Matsumoto, M. & Nishimura, T. (1998). "Mersenne Twister: A 623-dimensionally
 *   equidistributed uniform pseudo-random number generator." ACM Transactions
 *   on Modeling and Computer Simulation, 8(1), 3-30.
 * Box, G.E.P. & Muller, M.E. (1958). "A Note on the Generation of Random
 *   Normal Deviates." Annals of Mathematical Statistics, 29(2), 610-611.
 *
 * Author: Claudia Maria Lopez Bombin
 * License: MIT
 */

#include "rng.h"
#include <math.h>
#include <stdint.h>

/* ============================================================================
 * MT19937 INTERNAL CONSTANTS
 * ============================================================================
 *
 * These constants define the MT19937 algorithm parameters.
 *
 * MT_MATRIX_A: The twist transformation matrix coefficient.
 *   This is XOR'd with the state vector during the twist step.
 *   Value 0x9908B0DF is the standard MT19937 coefficient.
 *
 * MT_UPPER_MASK: Extracts the upper (most significant) bit of a 32-bit word.
 *   Used to split the state vector into upper and lower parts.
 *   0x80000000 = binary 10000000...0 (31 zeros)
 *
 * MT_LOWER_MASK: Extracts the lower 31 bits.
 *   0x7FFFFFFF = binary 01111111...1 (31 ones)
 *
 * Together, these split a 32-bit word into:
 *   upper bit (bit 31) and lower 31 bits (bits 0-30)
 * This separation is the core of the "twist" operation.
 */

#define MT_MATRIX_A   0x9908B0DFUL
#define MT_UPPER_MASK 0x80000000UL
#define MT_LOWER_MASK 0x7FFFFFFFUL

/* ============================================================================
 * seed_rng — Initialize the MT state from a 32-bit seed
 * ============================================================================
 *
 * ALGORITHM (from MT19937 specification):
 *
 * 1. mt[0] = seed
 * 2. For i = 1 to 623:
 *      mt[i] = (1812433253 * (mt[i-1] XOR (mt[i-1] >> 30)) + i)
 *      mt[i] &= 0xFFFFFFFF  (keep lower 32 bits)
 *
 * WHY THIS WORKS:
 * - The multiplier 1812433253 is specially chosen to distribute bits
 *   evenly across the state. It's a "good" constant discovered by the
 *   MT authors through extensive testing.
 * - The XOR and right-shift mix the bits of the previous state word.
 * - Adding i ensures each position gets a different value even if
 *   the seed has a pattern (like seed = 1).
 * - The & 0xFFFFFFFF simulates 32-bit unsigned integer overflow.
 *
 * After initialization, we set mti = MT_N (624) to force a twist
 * on the first call to rand_uniform(). This ensures the first
 * generated number is properly randomized.
 *
 * We also reset the Box-Muller cache (has_cached = 0) so the first
 * call to rand_normal() generates fresh normals.
 */

void seed_rng(RNGState *state, uint32_t seed) {
    int i;

    /* Initialize state vector from seed */
    state->mt[0] = seed & 0xFFFFFFFFUL;
    for (i = 1; i < MT_N; i++) {
        /*
         * Standard MT19937 initialization recurrence:
         * mt[i] = (multiplier * (mt[i-1] XOR (mt[i-1] >> 30)) + i) mod 2^32
         */
        state->mt[i] = (1812433253UL *
            (state->mt[i - 1] ^ (state->mt[i - 1] >> 30)) + i);
        /* Truncate to 32 bits (simulate uint32_t overflow) */
        state->mt[i] &= 0xFFFFFFFFUL;
    }
    /* Force twist on first rand_uniform() call */
    state->mti = MT_N;

    /* Reset Box-Muller cache */
    state->bm_has_cached = 0;
    state->bm_cached = 0.0;
}

/* ============================================================================
 * rand_uniform — Generate a uniform double in [0, 1)
 * ============================================================================
 *
 * ALGORITHM:
 * 1. If mti >= 624, perform the "twist" operation to regenerate the
 *    state vector.
 * 2. Extract mt[mti] and apply the tempering transformation.
 * 3. Scale to [0, 1) by multiplying by 2^-32.
 *
 * THE TWIST (when mti >= 624):
 * For k = 0 to 623, compute:
 *   y = (mt[k] & UPPER_MASK) | (mt[(k+1) % 624] & LOWER_MASK)
 *   mt[k] = mt[(k + 397) % 624] XOR (y >> 1) XOR mag01[y & 1]
 *
 * This linear feedback shift register operation creates the enormous
 * period of 2^19937-1.
 *
 * THE TEMPERING (applied each time we extract mt[mti]):
 * This is a series of bitwise operations that "temper" the bits
 * to improve the distribution of the output (the raw mt[] state
 * is not yet perfectly uniform in its bits).
 *
 *   y ^= (y >> 11);           // Mix upper bits down
 *   y ^= (y << 7) & 0x9D2C5680;  // Mix with magic constant
 *   y ^= (y << 15) & 0xEFC60000; // Mix more
 *   y ^= (y >> 18);           // Final mix
 *
 * SCALING TO [0, 1):
 * Multiply by 1/2^32 = 1/4294967296. This is exact in double precision
 * for all generated integers.
 *
 * Returns: double in [0.0, 1.0). Note: 1.0 is excluded.
 * This is important for the Box-Muller log(1-u) which requires u ∈ (0,1].
 * We use u1 = max(1e-300, u1) to avoid log(0) in the caller.
 */

double rand_uniform(RNGState *state) {
    /*
     * mag01 stores the matrix coefficient lookup:
     * mag01[0] = 0x0 = 0
     * mag01[1] = MT_MATRIX_A = 0x9908B0DF
     * Used in: mt[k] XOR (y>>1) XOR mag01[y & 1]
     * The least significant bit of y determines which matrix row we use.
     */
    static const uint32_t mag01[2] = {0x0UL, MT_MATRIX_A};
    uint32_t y;
    int kk;

    /* ====================================================================
     * TWIST: Regenerate the state vector when we've exhausted it
     * ====================================================================
     * The twist creates 624 new state words from the previous 624 words.
     * Each new word is a linear combination (XOR, shift) of two old words.
     */
    if (state->mti >= MT_N) {
        /*
         * First batch: k = 0...(N-M-1)
         * Here mt[k+M] is available without wrapping.
         * We combine mt[k] and mt[k+1] to create the new mt[k].
         */
        for (kk = 0; kk < MT_N - MT_M; kk++) {
            /* Split mt[kk] and mt[kk+1] into upper bit and lower 31 bits */
            y = (state->mt[kk] & MT_UPPER_MASK) |
                (state->mt[kk + 1] & MT_LOWER_MASK);
            /*
             * New mt[kk] = old mt[kk+M] XOR (y shifted right 1)
             *             XOR matrix coefficient (if y is odd)
             */
            state->mt[kk] = state->mt[kk + MT_M] ^ (y >> 1)
                          ^ mag01[y & 0x1UL];
        }

        /*
         * Second batch: k = (N-M)...(N-2)
         * Now mt[k+M] wraps around the array, so we use
         * mt[k + (M - N)] = mt[k + M - N].
         */
        for (; kk < MT_N - 1; kk++) {
            y = (state->mt[kk] & MT_UPPER_MASK) |
                (state->mt[kk + 1] & MT_LOWER_MASK);
            state->mt[kk] = state->mt[kk + (MT_M - MT_N)]
                          ^ (y >> 1) ^ mag01[y & 0x1UL];
        }

        /*
         * Final element: k = N-1
         * mt[(k+1) mod N] wraps around to mt[0].
         * mt[k+M] wraps to mt[M-1].
         */
        y = (state->mt[MT_N - 1] & MT_UPPER_MASK) |
            (state->mt[0] & MT_LOWER_MASK);
        state->mt[MT_N - 1] = state->mt[MT_M - 1]
                            ^ (y >> 1) ^ mag01[y & 0x1UL];

        /* Reset index: next call will use mt[0] */
        state->mti = 0;
    }

    /* ====================================================================
     * EXTRACT AND TEMPER
     * ====================================================================
     * Get the next state word and apply tempering transformations
     * to improve the statistical quality of the output bits.
     * Without tempering, the raw mt[] state doesn't produce
     * sufficiently random-looking sequences.
     */
    y = state->mt[state->mti++];

    /*
     * Tempering step 1: y ^= y >> 11
     * Shifts the upper 11 bits down and XORs with original.
     * This mixes the upper and lower halves.
     */
    y ^= (y >> 11);

    /*
     * Tempering step 2: y ^= (y << 7) & 0x9D2C5680
     * Shifts left 7, masks with a magic constant, XORs.
     * The constant 0x9D2C5680 was chosen to optimize equidistribution.
     */
    y ^= (y << 7) & 0x9D2C5680UL;

    /*
     * Tempering step 3: y ^= (y << 15) & 0xEFC60000
     * Similar to step 2 but with a different shift and mask.
     */
    y ^= (y << 15) & 0xEFC60000UL;

    /*
     * Tempering step 4: y ^= y >> 18
     * Final right-shift mix to scramble the remaining bits.
     */
    y ^= (y >> 18);

    /* ====================================================================
     * SCALE TO [0, 1)
     * ====================================================================
     * y is a 32-bit unsigned integer in [0, 2^32-1].
     * Multiply by 1/2^32 = 1/4294967296.0 to get [0, 1-2^-32).
     * This is exact in IEEE 754 double precision because 2^32 is
     * representable exactly and division by a power of 2 is exact.
     */
    return y * (1.0 / 4294967296.0);
}

/* ============================================================================
 * rand_normal — Generate a standard normal N(0,1) random variable
 * ============================================================================
 *
 * BOX-MULLER TRANSFORM:
 *
 * The fundamental problem: given a Uniform(0,1) generator, how do we
 * produce Normal(0,1) samples?
 *
 * The Box-Muller solution uses a clever trick from polar coordinates:
 *
 * 1. Generate U1, U2 ~ Uniform(0,1) independent.
 *
 * 2. Transform to polar coordinates:
 *      R = sqrt(-2 * ln(U1))
 *      Theta = 2 * pi * U2
 *
 * 3. Convert to Cartesian:
 *      Z1 = R * cos(Theta)
 *      Z2 = R * sin(Theta)
 *
 * Then Z1 and Z2 are independent N(0,1).
 *
 * WHY THIS WORKS (probability theory):
 * The joint distribution of two independent standard normals is:
 *   f(z1, z2) = (1/(2*pi)) * exp(-(z1^2 + z2^2)/2)
 *
 * In polar coordinates (r, theta):
 *   r^2 = z1^2 + z2^2
 *   f(r, theta) = (1/(2*pi)) * r * exp(-r^2/2)
 *
 * The radial part r has distribution r*exp(-r^2/2), which has CDF
 * 1 - exp(-r^2/2). By inverse CDF: r = sqrt(-2*ln(1-U)).
 * Since U and 1-U have the same distribution, r = sqrt(-2*ln(U)).
 *
 * The angular part theta is uniform on [0, 2*pi].
 *
 * CACHING OPTIMIZATION:
 * Box-Muller generates TWO normals from TWO uniforms. Rather than
 * wasting the second normal, we cache it and return it on the next
 * call. This means:
 * - Even calls: generate 2 uniforms, return Z1, cache Z2.
 * - Odd calls:  generate 0 uniforms, return cached Z2.
 * - Average: 1 uniform per normal (optimal for this method).
 *
 * NUMERICAL STABILITY:
 * If U1 = 0 exactly (probability 2^-32), log(0) = -inf, which
 * crashes. We guard with: if U1 < 1e-300, replace with 1e-300.
 * This has negligible impact on the distribution.
 *
 * ALTERNATIVES NOT IMPLEMENTED:
 * - Marsaglia polar method: avoids sin/cos but uses rejection sampling
 *   (rejects ~21.5% of the time). Slightly faster on some architectures
 *   but less predictable runtime.
 * - Ziggurat algorithm: much faster for large batches but complex to
 *   implement correctly. Overkill for our simulation sizes.
 */

double rand_normal(RNGState *state) {
    double u1, u2, r;

    /* Check if we have a cached normal from the previous call.
     * Box-Muller generates normals in pairs. We return one and
     * store the other for next time. This avoids wasting half
     * the entropy. */
    if (state->bm_has_cached) {
        state->bm_has_cached = 0;
        return state->bm_cached;
    }

    /* Generate two independent Uniform(0,1) random variables */
    u1 = rand_uniform(state);
    u2 = rand_uniform(state);

    /* Guard against log(0): if u1 is zero (extremely rare, probability
     * 2^-32), replace with a tiny positive number. This doesn't
     * meaningfully affect the distribution. */
    if (u1 < 1e-300) u1 = 1e-300;

    /* Box-Muller radial component:
     * r = sqrt(-2 * ln(u1)) comes from the inverse CDF of the
     * Rayleigh distribution. */
    r = sqrt(-2.0 * log(u1));

    /* Cache the second normal for next call:
     * Z2 = r * sin(2*pi*u2)
     * This avoids wasting a uniform sample. */
    state->bm_cached = r * sin(2.0 * M_PI * u2);
    state->bm_has_cached = 1;

    /* Return the first normal:
     * Z1 = r * cos(2*pi*u2) */
    return r * cos(2.0 * M_PI * u2);
}